### ISSUE TITLE
Medial Moodle Video Assignment Activity Issues 

### ISSUE THREAD

**Issue by gjrogala** [streamingltd/MEDIAL-Moodle-Submission#1]
Dear Medial Team

We started experiencing an issue with this plugin when students submit a video assignment in groups, with the group mode in the Assignment activity enabled. However, the plug-in works fine when the submission is individual so there must be a problem with the way the plug-in handles groups on Moodle.

Description:
Whenever grouped students are attempting to submit a video assignment, they are guided through the necessary steps to upload a video and the video upload progress bar completes. However at the end of the process when they click Save, they get an error message on top of the page saying "Nothing was Submitted". 

![a](https://user-images.githubusercontent.com/44284542/55053265-93699f00-5096-11e9-8e74-701bd75a1a51.jpeg)

Also, the submission status inside of the Assignment activity says that there is no submission. 

![b](https://user-images.githubusercontent.com/44284542/55053909-b85f1180-5098-11e9-8e20-9450724b33de.jpeg)

Finally, even though the submission status says that there is no submission, when you navigate to the Assignment activity and view all submissions, a link to the video appears in the Video Assignment column. In conclusion, it seems like the video is being uploaded but students still get the 'Nothing was Submitted' error message and the submission status says that there is no submission.

We rely on this plug-in for our formal assessment submissions so it would be great if this bug was fixed asap.

Thanks for your help!

**Comment by tim1mw** [comment]
Tidying up old issues, this was fixed some time ago.
