### ISSUE TITLE
4.3dev Fatal PHP error

### ISSUE THREAD

**Issue by aspark21** [streamingltd/MEDIAL-Moodle-Submission#3]
Moodle: master
helixassign: master

`'PHP Fatal error:  Declaration of assign_submission_helixassign::format_for_log(stdClass $submission) must be compatible with assign_plugin::format_for_log() in /var/www/html/mod/assign/submission/helixassign/locallib.php on line 360'`

**Comment by sharpchi** [comment]
This can safely be removed. This plugin supports M3.9+ This function was stopped being used in M2.7

**Comment by tim1mw** [comment]
This was initially dealt with in the 8.5.10 (2024012301) and has been removed in the latest development  version which will be pushed to this repo once QA has been done.
